export const ACTION_TYPE = {
	SET_CATEGORY: 'SET_CATEGORY',
	PAGE: 'PAGE',
	GET_USERS: 'GET_USERS',
	GET_ALL_USERS: 'GET_ALL_USERS',
	GET_USER: 'GET_USER',
	USER_CLEAR: 'USER_CLEAR',
	GET_SALARY_ANALYTICS: 'GET_SALARY_ANALYTICS',
};
